//! Tests for token source implementations.

mod str_graphql_token_source_lex_comment_byte_scanning_tests;
mod str_graphql_token_source_lex_name_byte_scanning_tests;
mod str_graphql_token_source_peek_consume_ascii_fast_path_tests;
mod str_graphql_token_source_skip_whitespace_byte_scanning_tests;
mod str_to_graphql_token_source_tests;
